[tak]
key_file="key.pem"
cert_file="cert.pem"
connection_id="TestConnection"
endpoint="ssl://127.0.0.1:8089"

[consumer]
catalyst_endpoint="https://gateway.catalyst.devintelops.io/graphql"
catalyst_token="eyJhbGciOiJFZERTQSJ9.eyJpc3MiOiJjYXRhbHlzdDpzeXN0ZW06and0OmxhdGVzdCIsInN1YiI6Im9yYmlzb3BzL2oudGF5bG9yQG9yYmlzb3BzLmNvbSIsImNsYWltcyI6WyJhZTgzMGYzYS03YWViLTQyNmYtYWU4OS0xYjM4Y2IyYTNkYmUiXSwiYXVkIjoiY2F0YWx5c3Q6c3lzdGVtOmRhdGFjaGFubmVscyIsImp0aSI6ImRmYzRiMzU5LTg3MWUtNGRjNy1iZTI4LWI4MGJhNjViNGUwMCIsIm5iZiI6MTcyOTEwNTg2MiwiaWF0IjoxNzI5MTA1ODYzLCJleHAiOjE3MzMzMzk0NjN9.4SzBsI-nAfT8FVJGzcRuF4zKTlK7PiUN93Cq-pMK2KSXFFVykygZRD0um8X02v1DcG0fKuPRr49_wKTnIEjwBA"
catalyst_query= """
query {
  aircraftWithinDistance(lat: 38.937620, lon: -77.180400, dist: 50) {
    hex
    flight
    lat
    lon
    alt_geom
  }
}
"""
catalyst_query_poll_interval_ms = 10000

[consumer.transforms.aircraftWithinDistance]
uid = "hex"
type = "a-f-A"
lat = "lat"
lon = "lon"
hae = "alt_geom"

[producer]
catalyst_jwks_url="http://localhost:8080/jwks"
catalyst_app_id = "thebestappid"