services:
  adapter:
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./key.pem:/app/key.pem"
      - "./cert.pem:/app/cert.pem"
      - "./config.toml:/app/config.toml"
    networks:
      tak-network:
    restart: unless-stopped
volumes:
  db_data:
networks:
  tak-network:
    name: tak-server_tak
    external: true
